name: React CI Simple Deployment

on:
  push:
    branches:
        "master"

jobs:
  build:
    runs-on: ubuntu-latest


    strategy:
      matrix:
        node-version: [x]

      steps:
          uses: actions/checkout@v1
          run: npm install
          run: npm run build
