name: React CI Simple Deployment

on:
  push:
    branches:
      - "master"

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: lts/*

    steps:
    - uses: actions/checkout@v1
    - name: Use Node LTS
      uses: actions/setup-node@v1
      with: ${{ matrix.node-version}} 
    - run: npm install
    - run: npm run build
